# Settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
permalink: pretty
future: true
timezone: America/New_York
repository: "robust-ml/robust-ml.github.io"

# Excludes
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - README.md

plugins:
  - "jekyll-github-metadata"
